version: '3.8'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - storage:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=storage
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ=Europe/Moscow
    ports:
      - "5432:5432"

volumes:
  storage:
